home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.get_home, name='home'),
    path('vehicles/', views.get_vehicles, name='vehicles'),
    path('services/', views.get_services, name='services'),
    path('featured/', views.get_featured, name='featured'),
    path('reviews/', views.get_reviews, name='reviews'),
    path('contact/', views.get_contact, name='contact'),
    path('login/', views.get_login.as_view(), name='login'),
    path('register/', views.get_register.as_view(), name='register'),
]

projectcuoiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from .form import LoginForm, RegisterForm
from django.views import View

# Create your views here.
def get_home(request):
    return render (request, 'home/home.html')

def get_vehicles(request):
    return render (request, 'home/vehicles.html')

def get_services(request):
    return render (request, 'home/services.html')

def get_featured(request):
    return render (request, 'home/featured.html')

def get_reviews(request):
    return render (request, 'home/reviews.html')

def get_contact(request):
    return render (request, 'home/contact.html')

class get_login(View):
    def get(self, request):
        lG = LoginForm
        return render(request, 'home/login.html', {'lG': lG})
    
class get_register(View):
    def get(self, request):
        rG = RegisterForm
        return render(request, 'home/register.html', {'rG': rG})

# def get_register(request):
#     return render (request, 'home/register.html')

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop Car Sports - {% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href=" {% static 'css/style.css' %}" type="text/css">

</head>

<body>

    <header class="header">

        <div id="menu-btn" class="fas fa-bars"></div>

        <a href="#" class="logo"> <span>max</span>wheels </a>

        <nav class="navbar">
            <a href={% url 'home:home' %}>home</a>
            <a href={% url 'home:vehicles' %}>vehicles</a>
            <a href={% url 'home:services' %}>services</a>
            <a href={% url 'home:featured' %}>featured</a>
            <a href={% url 'home:reviews' %}>reviews</a>
            <a href={% url 'home:contact' %}>contact</a>
        </nav>

        <div id="login-btn">
            <a href={% url 'home:login' %} class="btn">login</a>
            <i class="far fa-user"></i>
        </div>

    </header>

    <div class="login-form-container-none">

        <span id="close-login-form" class="fas fa-times"></span>

        <form action="">
            <h3>user login</h3>
            <input type="email" placeholder="email" class="box">
            <input type="password" placeholder="password" class="box">
            <p> forget your password <a href="#">click here</a> </p>
            <input type="submit" value="login" class="btn">
            <p>or login with</p>
            <div class="buttons">
                <a href="#" class="btn"> google </a>
                <a href="#" class="btn"> facebook </a>
            </div>
            <p> don't have an account <a href="#">create one</a> </p>
        </form>

    </div>

    <section class="home" id="home">

        <h3 data-speed="-2" class="home-parallax">find your car</h3>

        <img data-speed="5" class="home-parallax" src="{% static 'images/home-img.png' %}" alt="">

        <a data-speed="7" href="#" class="btn home-parallax">explore cars</a>

    </section>

    <section class="icons-container">

        <div class="icons">
            <i class="fas fa-home"></i>
            <div class="content">
                <h3>150+</h3>
                <p>branches</p>
            </div>
        </div>

        <div class="icons">
            <i class="fas fa-car"></i>
            <div class="content">
                <h3>4770+</h3>
                <p>cars sold</p>
            </div>
        </div>

        <div class="icons">
            <i class="fas fa-users"></i>
            <div class="content">
                <h3>320+</h3>
                <p>happy clients</p>
            </div>
        </div>

        <div class="icons">
            <i class="fas fa-car"></i>
            <div class="content">
                <h3>1500+</h3>
                <p>news cars</p>
            </div>
        </div>

    </section>

    {% block content %}{% endblock %}

    <section class="footer" id="footer">

        <div class="box-container">

            <div class="box">
                <h3>quick links</h3>
                <a href={% url 'home:home' %}> <i class="fas fa-arrow-right"></i> home </a>
                <a href={% url 'home:vehicles' %}> <i class="fas fa-arrow-right"></i> vehicles </a>
                <a href={% url 'home:services' %}> <i class="fas fa-arrow-right"></i> services </a>
                <a href={% url 'home:featured' %}> <i class="fas fa-arrow-right"></i> featured </a>
                <a href={% url 'home:reviews' %}> <i class="fas fa-arrow-right"></i> reviews </a>
                <a href={% url 'home:contact' %}> <i class="fas fa-arrow-right"></i> contact </a>
            </div>

            <div class="box">
                <h3>our branches</h3>
                <a href="#"> <i class="fas fa-map-marker-alt"></i> Viet Nam </a>
            </div>

            <div class="box">
                <h3>contact info</h3>
                <a href="#"> <i class="fab fa-facebook-f"></i> facebook </a>
                <a href="#"> <i class="fab fa-pinterest"></i> zalo </a>
                <a href="#"> <i class="fab fa-twitter"></i> twitter </a>
                <a href="#"> <i class="fab fa-instagram"></i> instagram </a>
            </div>

            <div class="box">
                <h3>contact info</h3>
                <a href="#"> <i class="fas fa-phone"></i> 0383508975 </a>
                <a href="#"> <i class="fas fa-envelope"></i> minhhh2004110025@student.giadinh.edu.vn </a>
                <a href="#"> <i class="fas fa-map-marker-alt"></i> Ho Chi Minh City </a>
            </div>

        </div>

        <div class="credit"> created by Huynh Huu Minh | K14DCPM01 | MSSV: 2004110025 </div>

    </section>

    <script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>

    <script src="{% static 'js/script.js' %}"></script>  

</body>

</html>

home/templates/home/contact.html
{% extends 'home/base.html' %} 

{% block title %}Contact{% endblock %} 

{% block content %}
{% load static %}

<section class="contact" id="contact">
  <h1 class="heading"><span>contact</span> us</h1>

  <div class="row">
    <iframe
      class="map"
      src="https://maps.google.com/maps?q=Hồ Chí Minh&t=&z=10&ie=UTF8&iwloc=&output=embed"
      frameborder="0"
      scrolling="no"
      marginheight="0"
      marginwidth="0"
      allowfullscreen=""
      loading="lazy"
    ></iframe>

    <form action="">
      <h3>get in touch</h3>
      <input type="text" placeholder="your name" class="box" />
      <input type="email" placeholder="your email" class="box" />
      <input type="tel" placeholder="subject" class="box" />
      <textarea
        placeholder="your message"
        class="box"
        cols="30"
        rows="10"
      ></textarea>
      <input type="submit" value="send message" class="btn" />
    </form>
  </div>
</section>

{% endblock %}

home/templates/home/featured.html
{% extends 'home/base.html' %} 

{% block title %}Featured{% endblock %} 

{% block content %}

{% load static %}

<section class="featured" id="featured">
  <h1 class="heading"><span>featured</span> cars</h1>

  <div class="swiper featured-slider">
    <div class="swiper-wrapper">
      <div class="swiper-slide box">
        <img src="{% static 'images/car-1.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star-half-alt"></i>
          </div>
          <div class="price">$55,000/-</div>
          <a href="#" class="btn">check out</a>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/car-2.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star-half-alt"></i>
          </div>
          <div class="price">$55,000/-</div>
          <a href="#" class="btn">check out</a>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/car-3.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star-half-alt"></i>
          </div>
          <div class="price">$55,000/-</div>
          <a href="#" class="btn">check out</a>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/car-4.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star-half-alt"></i>
          </div>
          <div class="price">$55,000/-</div>
          <a href="#" class="btn">check out</a>
        </div>
      </div>
    </div>

    <div class="swiper-pagination"></div>
  </div>

  <div class="swiper featured-slider">
    <div class="swiper-wrapper">
      <div class="swiper-slide box">
        <img src="{% static 'images/car-5.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star-half-alt"></i>
          </div>
          <div class="price">$55,000/-</div>
          <a href="#" class="btn">check out</a>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/car-6.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star-half-alt"></i>
          </div>
          <div class="price">$55,000/-</div>
          <a href="#" class="btn">check out</a>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/car-7.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star-half-alt"></i>
          </div>
          <div class="price">$55,000/-</div>
          <a href="#" class="btn">check out</a>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/car-8.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star-half-alt"></i>
          </div>
          <div class="price">$55,000/-</div>
          <a href="#" class="btn">check out</a>
        </div>
      </div>
    </div>

    <div class="swiper-pagination"></div>
  </div>
</section>

{% endblock %}

home/templates/home/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop Car Sports - Login</title>

    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href=" {% static 'css/style.css' %}" type="text/css">

</head>

<body>

    <div class="login-form-container">

        <a href={% url 'home:home' %} id="close-login-form" class="fas fa-times"></a>

        <form action="{% url 'home:login' %}" method="POST">
            <h3>user login</h3>
            {% csrf_token %}
            {{lG.as_p}}
            <input class='btn' type="Submit" value='Login'>
            <p>
                Don't have an account ? <a href={% url 'home:register' %}>Register</a>
            </p>
        </form>
    </div>

</body>

</html>

home/templates/home/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop Car Sports - Register</title>

    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href=" {% static 'css/style.css' %}" type="text/css">

</head>

<body>

    <div class="login-form-container">

        <a href={% url 'home:home' %} id="close-login-form" class="fas fa-times"></a>

        <form action="">
            <form action="{% url 'home:register' %}" method="GET">
                <h3>user register</h3>
                {% csrf_token %}
                {{rG.as_p}}
                <input class='btn' type="Submit" value='Register'>
                <p>
                    Already have an account ? <a href={% url 'home:login' %}>Login</a>
                </p>
            </form>
        </form>

    </div>

</body>

</html>

home/templates/home/reviews.html
{% extends 'home/base.html' %} 

{% block title %}Reviews{% endblock %} 

{% block content %}

{% load static %}

<section class="reviews" id="reviews">
  <h1 class="heading">client's <span>review</span></h1>

  <div class="swiper review-slider">
    <div class="swiper-wrapper">
      <div class="swiper-slide box">
        <img src="{% static 'images/pic-1.png' %}" alt="" />
        <div class="content">
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam
            incidunt quod praesentium iusto id autem possimus assumenda at ut
            saepe.
          </p>
          <h3>john deo</h3>
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star-half-alt"></i>
          </div>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/pic-2.png' %}" alt="" />
        <div class="content">
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam
            incidunt quod praesentium iusto id autem possimus assumenda at ut
            saepe.
          </p>
          <h3>john deo</h3>
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star-half-alt"></i>
          </div>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/pic-3.png' %}" alt="" />
        <div class="content">
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam
            incidunt quod praesentium iusto id autem possimus assumenda at ut
            saepe.
          </p>
          <h3>john deo</h3>
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star-half-alt"></i>
          </div>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/pic-4.png' %}" alt="" />
        <div class="content">
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam
            incidunt quod praesentium iusto id autem possimus assumenda at ut
            saepe.
          </p>
          <h3>john deo</h3>
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star-half-alt"></i>
          </div>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/pic-5.png' %}" alt="" />
        <div class="content">
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam
            incidunt quod praesentium iusto id autem possimus assumenda at ut
            saepe.
          </p>
          <h3>john deo</h3>
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star-half-alt"></i>
          </div>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/pic-6.png' %}" alt="" />
        <div class="content">
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsam
            incidunt quod praesentium iusto id autem possimus assumenda at ut
            saepe.
          </p>
          <h3>john deo</h3>
          <div class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star-half-alt"></i>
          </div>
        </div>
      </div>
    </div>

    <div class="swiper-pagination"></div>
  </div>
</section>

{% endblock %}

home/templates/home/services.html
{% extends 'home/base.html' %} 

{% block title %}Services{% endblock %} 

{% block content %}

{% load static %}

<section class="services" id="services">
  <h1 class="heading">our <span>services</span></h1>

  <div class="box-container">
    <div class="box">
      <i class="fas fa-car"></i>
      <h3>car selling</h3>
      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corporis,
        nisi.
      </p>
      <a href="#" class="btn"> read more</a>
    </div>

    <div class="box">
      <i class="fas fa-tools"></i>
      <h3>parts repair</h3>
      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corporis,
        nisi.
      </p>
      <a href="#" class="btn"> read more</a>
    </div>

    <div class="box">
      <i class="fas fa-car-crash"></i>
      <h3>car insurance</h3>
      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corporis,
        nisi.
      </p>
      <a href="#" class="btn"> read more</a>
    </div>

    <div class="box">
      <i class="fas fa-car-battery"></i>
      <h3>battery replacement</h3>
      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corporis,
        nisi.
      </p>
      <a href="#" class="btn"> read more</a>
    </div>

    <div class="box">
      <i class="fas fa-gas-pump"></i>
      <h3>oil change</h3>
      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corporis,
        nisi.
      </p>
      <a href="#" class="btn"> read more</a>
    </div>

    <div class="box">
      <i class="fas fa-headset"></i>
      <h3>24/7 support</h3>
      <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corporis,
        nisi.
      </p>
      <a href="#" class="btn"> read more</a>
    </div>
  </div>
</section>

{% endblock %}

home/templates/home/vehicles.html
{% extends 'home/base.html' %} 

{% block title %}Vehicles{% endblock %} 

{% block content %}
{% load static %}
<section class="vehicles" id="vehicles">
  <h1 class="heading">popular <span>vehicles</span></h1>

  <div class="swiper vehicles-slider">
    <div class="swiper-wrapper">
      <div class="swiper-slide box">
        <img src="{% static 'images/vehicle-1.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="price"><span>price : </span> $62,000/-</div>
          <p>
            new
            <span class="fas fa-circle"></span> 2021
            <span class="fas fa-circle"></span> automatic
            <span class="fas fa-circle"></span> petrol
            <span class="fas fa-circle"></span> 183mph
          </p>
          <a href="#" class="btn">check out</a>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/vehicle-2.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="price"><span>price : </span> $62,000/-</div>
          <p>
            new
            <span class="fas fa-circle"></span> 2021
            <span class="fas fa-circle"></span> automatic
            <span class="fas fa-circle"></span> petrol
            <span class="fas fa-circle"></span> 183mph
          </p>
          <a href="#" class="btn">check out</a>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/vehicle-3.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="price"><span>price : </span> $62,000/-</div>
          <p>
            new
            <span class="fas fa-circle"></span> 2021
            <span class="fas fa-circle"></span> automatic
            <span class="fas fa-circle"></span> petrol
            <span class="fas fa-circle"></span> 183mph
          </p>
          <a href="#" class="btn">check out</a>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/vehicle-4.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="price"><span>price : </span> $62,000/-</div>
          <p>
            new
            <span class="fas fa-circle"></span> 2021
            <span class="fas fa-circle"></span> automatic
            <span class="fas fa-circle"></span> petrol
            <span class="fas fa-circle"></span> 183mph
          </p>
          <a href="#" class="btn">check out</a>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/vehicle-5.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="price"><span>price : </span> $62,000/-</div>
          <p>
            new
            <span class="fas fa-circle"></span> 2021
            <span class="fas fa-circle"></span> automatic
            <span class="fas fa-circle"></span> petrol
            <span class="fas fa-circle"></span> 183mph
          </p>
          <a href="#" class="btn">check out</a>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/vehicle-6.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="price"><span>price : </span> $62,000/-</div>
          <p>
            new
            <span class="fas fa-circle"></span> 2021
            <span class="fas fa-circle"></span> automatic
            <span class="fas fa-circle"></span> petrol
            <span class="fas fa-circle"></span> 183mph
          </p>
          <a href="#" class="btn">check out</a>
        </div>
      </div>
    </div>

    <div class="swiper-pagination"></div>
  </div>
  <div class="swiper vehicles-slider">
    <div class="swiper-wrapper">
      <div class="swiper-slide box">
        <img src="{% static 'images/vehicle-1.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="price"><span>price : </span> $62,000/-</div>
          <p>
            new
            <span class="fas fa-circle"></span> 2021
            <span class="fas fa-circle"></span> automatic
            <span class="fas fa-circle"></span> petrol
            <span class="fas fa-circle"></span> 183mph
          </p>
          <a href="#" class="btn">check out</a>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/vehicle-2.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="price"><span>price : </span> $62,000/-</div>
          <p>
            new
            <span class="fas fa-circle"></span> 2021
            <span class="fas fa-circle"></span> automatic
            <span class="fas fa-circle"></span> petrol
            <span class="fas fa-circle"></span> 183mph
          </p>
          <a href="#" class="btn">check out</a>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/vehicle-3.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="price"><span>price : </span> $62,000/-</div>
          <p>
            new
            <span class="fas fa-circle"></span> 2021
            <span class="fas fa-circle"></span> automatic
            <span class="fas fa-circle"></span> petrol
            <span class="fas fa-circle"></span> 183mph
          </p>
          <a href="#" class="btn">check out</a>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/vehicle-4.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="price"><span>price : </span> $62,000/-</div>
          <p>
            new
            <span class="fas fa-circle"></span> 2021
            <span class="fas fa-circle"></span> automatic
            <span class="fas fa-circle"></span> petrol
            <span class="fas fa-circle"></span> 183mph
          </p>
          <a href="#" class="btn">check out</a>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/vehicle-5.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="price"><span>price : </span> $62,000/-</div>
          <p>
            new
            <span class="fas fa-circle"></span> 2021
            <span class="fas fa-circle"></span> automatic
            <span class="fas fa-circle"></span> petrol
            <span class="fas fa-circle"></span> 183mph
          </p>
          <a href="#" class="btn">check out</a>
        </div>
      </div>

      <div class="swiper-slide box">
        <img src="{% static 'images/vehicle-6.png' %}" alt="" />
        <div class="content">
          <h3>new model</h3>
          <div class="price"><span>price : </span> $62,000/-</div>
          <p>
            new
            <span class="fas fa-circle"></span> 2021
            <span class="fas fa-circle"></span> automatic
            <span class="fas fa-circle"></span> petrol
            <span class="fas fa-circle"></span> 183mph
          </p>
          <a href="#" class="btn">check out</a>
        </div>
      </div>
    </div>

    <div class="swiper-pagination"></div>
  </div>
</section>
{% endblock %}